// Accounting Foundation Types - Explicit Double-Entry with Audit Trails
// Based on ACCOUNTING_FOUNDATION_MIGRATION_PLAN.md

import type { CurrencyCode } from '@pos-platform/shared';

export type AssetSubClassification = 'current_asset' | 'non_current_asset';
export type LiabilitySubClassification = 'current_liability' | 'non_current_liability';
export type EquitySubClassification = 'equity';
export type AccountSubClassification =
  | AssetSubClassification
  | LiabilitySubClassification
  | EquitySubClassification;

/**
 * Per-currency debit/credit map for a journal entry (Phase 11 generalization).
 * Each row is self-describing — the keys carry the currency identity, so
 * a row written for an AED store is always interpretable regardless of
 * the store's later configuration changes.
 */
export type JournalEntryAmounts = Partial<Record<CurrencyCode, { debit: number; credit: number }>>;

/** Per-currency running balance map for a balance snapshot (Phase 11). */
export type BalanceSnapshotMap = Partial<Record<CurrencyCode, number>>;

/**
 * Journal Entry - Source of Truth for all financial transactions
 * Every financial transaction creates at least two journal entries (debit + credit)
 *
 * Phase 11 dual-write: rows now carry both the deprecated USD/LBP scalar
 * columns and the self-describing `amounts` map. The map is the
 * authority for new code; the scalars are kept until 11d (column drop).
 */
export interface JournalEntry {
  id: string;
  store_id: string;
  branch_id: string | null;      // Future: multiple branches
  transaction_id: string;         // Groups debit + credit entries
  account_code: string;           // '1100', '1200', etc.
  account_name: string;
  /** Self-describing per-currency map. Immutable once written. */
  amounts: JournalEntryAmounts;
  entity_id: string;              // NEVER NULL - references entities table
  entity_type: 'customer' | 'supplier' | 'employee' | 'cash' | 'internal';
  posted_date: string;
  fiscal_period: string;
  is_posted: boolean;
  description?: string;           // Optional description for the entry
  created_at: string;
  created_by: string | null;  // User ID (UUID) - null for system-generated
  _synced: boolean;
  // New fields for reversal/reactivation tracking (replaces string parsing)
  bill_id?: string | null;        // Direct link to bill - enables fast queries
  reversal_of_journal_entry_id?: string | null;  // Links reversal entry to original entry
  entry_type?: 'original' | 'reversal' | 'reactivation';  // Explicit type instead of parsing description
  transfer_group_id?: string | null;
}

/**
 * Balance Snapshots - Performance optimization for historical queries
 * Stores account balances at specific points in time.
 *
 * Phase 11 dual-write: rows now carry both the deprecated USD/LBP
 * scalar columns and the self-describing `balances` map.
 */
export interface BalanceSnapshot {
  id: string;
  store_id: string;
  branch_id: string | null;
  account_code: string;
  entity_id: string | null;
  /** Self-describing per-currency map. */
  balances: BalanceSnapshotMap;
  snapshot_date: string;
  snapshot_type: 'hourly' | 'daily' | 'end_of_day';
  verified: boolean;
  /**
   * Plan B: TRUE when an underlying journal entry has been edited and the
   * snapshot must be recomputed before next use. Set by the server-side
   * invalidation trigger; cleared by the nightly recompute pass. The read
   * path treats stale rows as missing.
   */
  stale?: boolean;
  /**
   * Plan B / Plan C: TRUE for fiscal-year-end closing snapshots. Immutable
   * anchor — never recomputed, never overridden.
   */
  is_closing?: boolean;
  /**
   * Plan B: origin of the row.
   *   'server'  — canonical, generated by the nightly Postgres function.
   *   'client'  — local-only fallback for long-offline periods. NEVER uploaded.
   *   'closing' — year-end close anchor.
   * Conflict precedence on (store, account, entity, date): closing > server > client.
   */
  source?: 'server' | 'client' | 'closing';
  created_at: string;
  _synced: boolean;
}

/**
 * Entities - Unified abstraction for customers, suppliers, employees, cash, etc.
 * Replaces separate customers/suppliers tables with unified entity management
 */
export interface Entity {
  id: string;
  store_id: string;
  branch_id: string | null;
  entity_type: 'customer' | 'supplier' | 'employee' | 'cash' | 'internal';
  entity_code: string;
  name: string;
  phone: string | null;
  is_system_entity: boolean;      // true for "Cash Customer", "Internal", etc.
  is_active: boolean;
  customer_data: object | null;   // Type-specific JSON data
  supplier_data: object | null;
  created_at: string;
  updated_at: string;
  _synced: boolean;
}

/**
 * Chart of Accounts - Configuration for account types and rules
 */
export interface ChartOfAccounts {
  id: string;
  store_id: string;
  account_code: string;           // '1100'
  account_name: string;           // 'Cash'
  account_type: 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';
  sub_classification: AccountSubClassification | null;
  requires_entity: boolean;       // Whether this account requires an entity_id
  is_active: boolean;
}

/**
 * Customer-specific data structure for entity.customer_data
 */
export interface CustomerData {
  /** Per-currency credit-limit map (primary surface). */
  max_balances?: Partial<Record<CurrencyCode, number>>;
  /** @deprecated Use `max_balances.LBP`. Kept as a back-compat mirror. */
  lb_max_balance?: number;
  credit_limit?: number;
  payment_terms?: string;
  discount_rate?: number;
}

/**
 * Supplier-specific data structure for entity.supplier_data
 */
export interface SupplierData {
  type: 'commission' | 'direct';
  commission_rate?: number;
  payment_terms?: string;
  /** Per-currency advance-payment map (primary surface). */
  advance_balances?: Partial<Record<CurrencyCode, number>>;
  /** @deprecated Use `advance_balances.LBP`. */
  advance_lb_balance?: number;
  /** @deprecated Use `advance_balances.USD`. */
  advance_usd_balance?: number;
}

/**
 * Employee-specific data structure for entity.employee_data
 */
export interface EmployeeData {
  email?: string;
  role?: 'admin' | 'manager' | 'cashier';
  monthly_salary?: string;
  working_hours_start?: string;
  working_hours_end?: string;
  working_days?: string;
}

/**
 * Transaction result for atomic operations
 */
export interface TransactionResult {
  success: boolean;
  transactionId: string;
  journalEntries: JournalEntry[];
  error?: string;
}

/**
 * Journal entry creation parameters
 * Supports both USD and LBP amounts in a single entry
 */
export interface CreateJournalEntryParams {
  transactionId: string;
  debitAccount: string;
  creditAccount: string;
  amountUSD?: number;              // USD amount (optional, defaults to 0)
  amountLBP?: number;              // LBP amount (optional, defaults to 0)
  entityId: string;
  description?: string;
  postedDate?: string;
  createdBy?: string | null;  // User ID (UUID) - null for system-generated
  branchId: string;  // Branch ID - required, must match transaction.branch_id
  // Legacy single-currency entry shape (kept for backward callers).
  amount?: number;
  currency?: CurrencyCode;
  skipVerification?: boolean;      // Skip verification queries when called within a transaction (prevents PrematureCommitError)
}

/**
 * Balance calculation result.
 *
 * USD/LBP fields preserved for legacy callers; new code should use
 * `byCurrency` directly.
 */
export interface BalanceResult {
  USD: number;
  LBP: number;
  byCurrency?: Partial<Record<CurrencyCode, number>>;
  lastCalculated: string;
}

/**
 * Fiscal period helper type
 */
export interface FiscalPeriod {
  year: number;
  month: number;
  period: string; // Format: "YYYY-MM"
}
