-- =========================================================================
--  balance_snapshots — stale flag + source attribution + closing flag
--  (Plan B, Phase B2)
--
--  Purpose:
--    1. Add `stale` boolean — marks a snapshot whose underlying journal
--       entries have been edited and therefore needs recomputation.
--       Maintained by the trigger added in Phase B4.
--    2. Add `is_closing` boolean — denormalized flag for FY-end snapshots
--       (Plan C year-end close). Closing snapshots are immutable anchors;
--       the read path (Phase B6) treats them as the highest-priority source.
--    3. Add `source` text — three valid origins of a snapshot row:
--          'server'  — generated by the nightly Postgres function (B3).
--                       Canonical and replicated to all devices.
--          'client'  — generated locally on a device during long-offline
--                       periods to keep balance-lookup performance bounded.
--                       LOCAL-ONLY; never uploaded.
--          'closing' — generated at year-end close. Immutable.
--    4. Conflict precedence honored by the read path: closing > server >
--       client. Sync replaces a local client snapshot with an arriving
--       server snapshot for the same (store, account, entity, date).
--
--  See OFFLINE_HISTORY_ARCHITECTURE.md §5.2 and the hybrid offline strategy
--  agreed during Plan B kickoff.
-- =========================================================================

BEGIN;

-- -------------------------------------------------------------------------
-- 1. New columns
-- -------------------------------------------------------------------------
ALTER TABLE public.balance_snapshots
  ADD COLUMN IF NOT EXISTS stale boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_closing boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'client';

-- Allowed source values. Added as a separate constraint (rather than CHECK
-- inline) so we can DROP/replace it cleanly when new sources are introduced.
ALTER TABLE public.balance_snapshots
  DROP CONSTRAINT IF EXISTS balance_snapshots_source_valid;
ALTER TABLE public.balance_snapshots
  ADD CONSTRAINT balance_snapshots_source_valid
    CHECK (source IN ('server', 'client', 'closing'));

-- A closing snapshot must always be sourced from the closing pipeline —
-- this prevents accidental marking by client generation.
ALTER TABLE public.balance_snapshots
  DROP CONSTRAINT IF EXISTS balance_snapshots_closing_source_match;
ALTER TABLE public.balance_snapshots
  ADD CONSTRAINT balance_snapshots_closing_source_match
    CHECK ((is_closing = false) OR (source = 'closing'));

COMMENT ON COLUMN public.balance_snapshots.stale IS
  'TRUE when an underlying journal entry has been edited and the row must '
  'be recomputed before next use. Set by the journal-entry invalidation '
  'trigger (B4); cleared by the nightly recompute pass (B5). The read '
  'path treats stale rows as missing.';

COMMENT ON COLUMN public.balance_snapshots.is_closing IS
  'TRUE for fiscal-year-end closing snapshots (Plan C). Immutable anchors — '
  'never recomputed, never overridden by daily snapshot generation. Read '
  'path treats them as the highest-priority opening-balance source.';

COMMENT ON COLUMN public.balance_snapshots.source IS
  'Origin: ''server'' (canonical, generated by nightly Postgres function), '
  '''client'' (local-only fallback for offline gaps; never uploaded), or '
  '''closing'' (year-end close anchor). On conflict for the same (store, '
  'account, entity, date), precedence is closing > server > client.';

-- -------------------------------------------------------------------------
-- 2. Indexes
-- -------------------------------------------------------------------------
-- Partial index for the nightly stale-recompute pass — only TRUE rows are
-- relevant, and most rows are FALSE, so a partial index stays tiny.
CREATE INDEX IF NOT EXISTS idx_balance_snapshots_stale
  ON public.balance_snapshots (store_id, snapshot_date)
  WHERE stale = true;

-- Lookups by source within a store (e.g. "find local-only client rows for
-- this store" or "list all closing snapshots"). Cheap; supports admin tools.
CREATE INDEX IF NOT EXISTS idx_balance_snapshots_store_source
  ON public.balance_snapshots (store_id, source);

-- Direct lookup of closing snapshots by date — used by Plan C year-end
-- queries and the read-path "is there a closing snapshot for this exact
-- date?" check.
CREATE INDEX IF NOT EXISTS idx_balance_snapshots_closing
  ON public.balance_snapshots (store_id, account_code, entity_id, snapshot_date)
  WHERE is_closing = true;

-- -------------------------------------------------------------------------
-- 3. Backfill: existing rows were all written by the client scheduler.
-- -------------------------------------------------------------------------
-- The default for `source` is 'client', so existing rows are already
-- correctly attributed. Still, make it explicit for safety against future
-- DEFAULT changes.
UPDATE public.balance_snapshots
SET source = 'client'
WHERE source IS NULL OR source = '';

COMMIT;
